# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
    backend "s3" {
        bucket = "terraform-statefile-aws"
        key = "./terraform.tfstate"
        region = "us-east-1"
        encrypt = true
    }
}
